// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: algo.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCategoryBaseline = `-- name: GetCategoryBaseline :one
SELECT category, median FROM category_baselines WHERE category = $1
`

func (q *Queries) GetCategoryBaseline(ctx context.Context, category string) (CategoryBaseline, error) {
	row := q.db.QueryRow(ctx, getCategoryBaseline, category)
	var i CategoryBaseline
	err := row.Scan(&i.Category, &i.Median)
	return i, err
}

const getCycleState = `-- name: GetCycleState :one
SELECT talent_id, cycle_id, cycle_number, pdc_allocated, pdc_next, pattern, delta_st, updated_at FROM talent_cycle_states WHERE talent_id = $1 AND cycle_id = $2
`

type GetCycleStateParams struct {
	TalentID string
	CycleID  string
}

func (q *Queries) GetCycleState(ctx context.Context, arg GetCycleStateParams) (TalentCycleState, error) {
	row := q.db.QueryRow(ctx, getCycleState, arg.TalentID, arg.CycleID)
	var i TalentCycleState
	err := row.Scan(
		&i.TalentID,
		&i.CycleID,
		&i.CycleNumber,
		&i.PdcAllocated,
		&i.PdcNext,
		&i.Pattern,
		&i.DeltaSt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyOutputs = `-- name: GetDailyOutputs :many
SELECT COUNT(*)::float8 AS daily_count
FROM conversion_events
WHERE talent_id = $1 AND cycle_id = $2
GROUP BY DATE(occurred_at AT TIME ZONE 'UTC')
ORDER BY DATE(occurred_at AT TIME ZONE 'UTC')
`

type GetDailyOutputsParams struct {
	TalentID string
	CycleID  string
}

func (q *Queries) GetDailyOutputs(ctx context.Context, arg GetDailyOutputsParams) ([]float64, error) {
	rows, err := q.db.Query(ctx, getDailyOutputs, arg.TalentID, arg.CycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []float64{}
	for rows.Next() {
		var daily_count float64
		if err := rows.Scan(&daily_count); err != nil {
			return nil, err
		}
		items = append(items, daily_count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTalentBaseline = `-- name: GetTalentBaseline :one
SELECT talent_id, alpha_lt, beta_lt, lambda_lt, sigma_hist, delta_lt, updated_at FROM talent_baselines WHERE talent_id = $1
`

func (q *Queries) GetTalentBaseline(ctx context.Context, talentID string) (TalentBaseline, error) {
	row := q.db.QueryRow(ctx, getTalentBaseline, talentID)
	var i TalentBaseline
	err := row.Scan(
		&i.TalentID,
		&i.AlphaLt,
		&i.BetaLt,
		&i.LambdaLt,
		&i.SigmaHist,
		&i.DeltaLt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTalentOutputWindow = `-- name: GetTalentOutputWindow :many
SELECT COUNT(*)::float8 AS daily_count
FROM conversion_events
WHERE talent_id = $1
  AND occurred_at >= NOW() - ($2::int * INTERVAL '1 day')
GROUP BY DATE(occurred_at AT TIME ZONE 'UTC')
ORDER BY DATE(occurred_at AT TIME ZONE 'UTC')
`

type GetTalentOutputWindowParams struct {
	TalentID string
	Column2  int32
}

func (q *Queries) GetTalentOutputWindow(ctx context.Context, arg GetTalentOutputWindowParams) ([]float64, error) {
	rows, err := q.db.Query(ctx, getTalentOutputWindow, arg.TalentID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []float64{}
	for rows.Next() {
		var daily_count float64
		if err := rows.Scan(&daily_count); err != nil {
			return nil, err
		}
		items = append(items, daily_count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTalentTodayOutput = `-- name: GetTalentTodayOutput :one
SELECT COUNT(*)::float8 FROM conversion_events
WHERE talent_id = $1
  AND DATE(occurred_at AT TIME ZONE 'UTC') = DATE($2 AT TIME ZONE 'UTC')
`

type GetTalentTodayOutputParams struct {
	TalentID string
	Timezone interface{}
}

func (q *Queries) GetTalentTodayOutput(ctx context.Context, arg GetTalentTodayOutputParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTalentTodayOutput, arg.TalentID, arg.Timezone)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertCycleState = `-- name: UpsertCycleState :exec
INSERT INTO talent_cycle_states (talent_id, cycle_id, cycle_number, pdc_allocated,
  pdc_next, pattern, delta_st, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
ON CONFLICT (talent_id, cycle_id) DO UPDATE SET
  pdc_allocated = EXCLUDED.pdc_allocated,
  pdc_next      = EXCLUDED.pdc_next,
  pattern       = EXCLUDED.pattern,
  delta_st      = EXCLUDED.delta_st,
  updated_at    = EXCLUDED.updated_at
`

type UpsertCycleStateParams struct {
	TalentID     string
	CycleID      string
	CycleNumber  int32
	PdcAllocated float64
	PdcNext      float64
	Pattern      string
	DeltaSt      float64
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertCycleState(ctx context.Context, arg UpsertCycleStateParams) error {
	_, err := q.db.Exec(ctx, upsertCycleState,
		arg.TalentID,
		arg.CycleID,
		arg.CycleNumber,
		arg.PdcAllocated,
		arg.PdcNext,
		arg.Pattern,
		arg.DeltaSt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTalentBaseline = `-- name: UpsertTalentBaseline :exec
INSERT INTO talent_baselines (talent_id, alpha_lt, beta_lt, lambda_lt, sigma_hist,
  delta_lt, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,NOW())
ON CONFLICT (talent_id) DO UPDATE SET
  alpha_lt   = EXCLUDED.alpha_lt,
  beta_lt    = EXCLUDED.beta_lt,
  lambda_lt  = EXCLUDED.lambda_lt,
  sigma_hist = EXCLUDED.sigma_hist,
  delta_lt   = EXCLUDED.delta_lt,
  updated_at = EXCLUDED.updated_at
`

type UpsertTalentBaselineParams struct {
	TalentID  string
	AlphaLt   float64
	BetaLt    float64
	LambdaLt  float64
	SigmaHist float64
	DeltaLt   float64
}

func (q *Queries) UpsertTalentBaseline(ctx context.Context, arg UpsertTalentBaselineParams) error {
	_, err := q.db.Exec(ctx, upsertTalentBaseline,
		arg.TalentID,
		arg.AlphaLt,
		arg.BetaLt,
		arg.LambdaLt,
		arg.SigmaHist,
		arg.DeltaLt,
	)
	return err
}
