// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package postgres

import (
	"context"
)

const createAssignment = `-- name: CreateAssignment :exec
INSERT INTO talent_assignments (talent_id, campaign_id, cycle_id, slot_id, role_label,
  status, assignment_source, pdc_mode, pdc_value, match_score, match_dm, match_gp,
  match_oh, pinned_tier, effective_tier, breakout_flag)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type CreateAssignmentParams struct {
	TalentID         string
	CampaignID       string
	CycleID          string
	SlotID           string
	RoleLabel        string
	Status           string
	AssignmentSource string
	PdcMode          string
	PdcValue         float64
	MatchScore       float64
	MatchDm          float64
	MatchGp          float64
	MatchOh          float64
	PinnedTier       int32
	EffectiveTier    int32
	BreakoutFlag     bool
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) error {
	_, err := q.db.Exec(ctx, createAssignment,
		arg.TalentID,
		arg.CampaignID,
		arg.CycleID,
		arg.SlotID,
		arg.RoleLabel,
		arg.Status,
		arg.AssignmentSource,
		arg.PdcMode,
		arg.PdcValue,
		arg.MatchScore,
		arg.MatchDm,
		arg.MatchGp,
		arg.MatchOh,
		arg.PinnedTier,
		arg.EffectiveTier,
		arg.BreakoutFlag,
	)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT talent_id, campaign_id, cycle_id, slot_id, role_label, status, assignment_source, pdc_mode, pdc_value, match_score, match_dm, match_gp, match_oh, pinned_tier, effective_tier, breakout_flag, assigned_at FROM talent_assignments WHERE talent_id = $1 AND cycle_id = $2
`

type GetAssignmentParams struct {
	TalentID string
	CycleID  string
}

func (q *Queries) GetAssignment(ctx context.Context, arg GetAssignmentParams) (TalentAssignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, arg.TalentID, arg.CycleID)
	var i TalentAssignment
	err := row.Scan(
		&i.TalentID,
		&i.CampaignID,
		&i.CycleID,
		&i.SlotID,
		&i.RoleLabel,
		&i.Status,
		&i.AssignmentSource,
		&i.PdcMode,
		&i.PdcValue,
		&i.MatchScore,
		&i.MatchDm,
		&i.MatchGp,
		&i.MatchOh,
		&i.PinnedTier,
		&i.EffectiveTier,
		&i.BreakoutFlag,
		&i.AssignedAt,
	)
	return i, err
}

const listAssignedTalents = `-- name: ListAssignedTalents :many
SELECT talent_id, campaign_id, cycle_id, slot_id, role_label, status, assignment_source, pdc_mode, pdc_value, match_score, match_dm, match_gp, match_oh, pinned_tier, effective_tier, breakout_flag, assigned_at FROM talent_assignments WHERE cycle_id = $1 ORDER BY effective_tier DESC
`

func (q *Queries) ListAssignedTalents(ctx context.Context, cycleID string) ([]TalentAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignedTalents, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TalentAssignment{}
	for rows.Next() {
		var i TalentAssignment
		if err := rows.Scan(
			&i.TalentID,
			&i.CampaignID,
			&i.CycleID,
			&i.SlotID,
			&i.RoleLabel,
			&i.Status,
			&i.AssignmentSource,
			&i.PdcMode,
			&i.PdcValue,
			&i.MatchScore,
			&i.MatchDm,
			&i.MatchGp,
			&i.MatchOh,
			&i.PinnedTier,
			&i.EffectiveTier,
			&i.BreakoutFlag,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentsByTalent = `-- name: ListAssignmentsByTalent :many
SELECT talent_id, campaign_id, cycle_id, slot_id, role_label, status, assignment_source, pdc_mode, pdc_value, match_score, match_dm, match_gp, match_oh, pinned_tier, effective_tier, breakout_flag, assigned_at FROM talent_assignments WHERE talent_id = $1 ORDER BY assigned_at DESC
`

func (q *Queries) ListAssignmentsByTalent(ctx context.Context, talentID string) ([]TalentAssignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByTalent, talentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TalentAssignment{}
	for rows.Next() {
		var i TalentAssignment
		if err := rows.Scan(
			&i.TalentID,
			&i.CampaignID,
			&i.CycleID,
			&i.SlotID,
			&i.RoleLabel,
			&i.Status,
			&i.AssignmentSource,
			&i.PdcMode,
			&i.PdcValue,
			&i.MatchScore,
			&i.MatchDm,
			&i.MatchGp,
			&i.MatchOh,
			&i.PinnedTier,
			&i.EffectiveTier,
			&i.BreakoutFlag,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
