// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package postgres

import (
	"context"
)

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_id, action_type, entity_type, entity_id, before_state, after_state, created_at FROM audit_log
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListAuditLogParams struct {
	EntityType string
	EntityID   string
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActionType,
			&i.EntityType,
			&i.EntityID,
			&i.BeforeState,
			&i.AfterState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_log (id, actor_id, action_type, entity_type, entity_id,
  before_state, after_state)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type WriteAuditLogParams struct {
	ID          string
	ActorID     string
	ActionType  string
	EntityType  string
	EntityID    string
	BeforeState []byte
	AfterState  []byte
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.ID,
		arg.ActorID,
		arg.ActionType,
		arg.EntityType,
		arg.EntityID,
		arg.BeforeState,
		arg.AfterState,
	)
	return err
}
