// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package postgres

import (
	"context"
)

const createBrand = `-- name: CreateBrand :exec
INSERT INTO brands (id, name, shortcode, industry, description, website, status)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type CreateBrandParams struct {
	ID          string
	Name        string
	Shortcode   string
	Industry    string
	Description string
	Website     string
	Status      string
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) error {
	_, err := q.db.Exec(ctx, createBrand,
		arg.ID,
		arg.Name,
		arg.Shortcode,
		arg.Industry,
		arg.Description,
		arg.Website,
		arg.Status,
	)
	return err
}

const createBrandContact = `-- name: CreateBrandContact :exec
INSERT INTO brand_contacts (id, brand_id, first_name, last_name, role, email,
  whatsapp_number, viewer_token, access_password_hash, token_active)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreateBrandContactParams struct {
	ID                 string
	BrandID            string
	FirstName          string
	LastName           string
	Role               string
	Email              string
	WhatsappNumber     string
	ViewerToken        string
	AccessPasswordHash string
	TokenActive        bool
}

func (q *Queries) CreateBrandContact(ctx context.Context, arg CreateBrandContactParams) error {
	_, err := q.db.Exec(ctx, createBrandContact,
		arg.ID,
		arg.BrandID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Email,
		arg.WhatsappNumber,
		arg.ViewerToken,
		arg.AccessPasswordHash,
		arg.TokenActive,
	)
	return err
}

const deactivateBrandContact = `-- name: DeactivateBrandContact :exec
UPDATE brand_contacts SET token_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateBrandContact(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateBrandContact, id)
	return err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, name, shortcode, industry, description, website, status, created_at, updated_at FROM brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shortcode,
		&i.Industry,
		&i.Description,
		&i.Website,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandByShortcode = `-- name: GetBrandByShortcode :one
SELECT id, name, shortcode, industry, description, website, status, created_at, updated_at FROM brands WHERE shortcode = $1
`

func (q *Queries) GetBrandByShortcode(ctx context.Context, shortcode string) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByShortcode, shortcode)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Shortcode,
		&i.Industry,
		&i.Description,
		&i.Website,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandContactByID = `-- name: GetBrandContactByID :one
SELECT id, brand_id, first_name, last_name, role, email, whatsapp_number, viewer_token, access_password_hash, token_active, future_user_account_id, created_at, updated_at FROM brand_contacts WHERE id = $1
`

func (q *Queries) GetBrandContactByID(ctx context.Context, id string) (BrandContact, error) {
	row := q.db.QueryRow(ctx, getBrandContactByID, id)
	var i BrandContact
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.WhatsappNumber,
		&i.ViewerToken,
		&i.AccessPasswordHash,
		&i.TokenActive,
		&i.FutureUserAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandContactByViewerToken = `-- name: GetBrandContactByViewerToken :one
SELECT id, brand_id, first_name, last_name, role, email, whatsapp_number, viewer_token, access_password_hash, token_active, future_user_account_id, created_at, updated_at FROM brand_contacts WHERE viewer_token = $1 AND token_active = true
`

func (q *Queries) GetBrandContactByViewerToken(ctx context.Context, viewerToken string) (BrandContact, error) {
	row := q.db.QueryRow(ctx, getBrandContactByViewerToken, viewerToken)
	var i BrandContact
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.WhatsappNumber,
		&i.ViewerToken,
		&i.AccessPasswordHash,
		&i.TokenActive,
		&i.FutureUserAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBrandContactForAuth = `-- name: GetBrandContactForAuth :one
SELECT id, brand_id, first_name, last_name, role, email, whatsapp_number, viewer_token, access_password_hash, token_active, future_user_account_id, created_at, updated_at FROM brand_contacts WHERE viewer_token = $1 AND token_active = true
`

func (q *Queries) GetBrandContactForAuth(ctx context.Context, viewerToken string) (BrandContact, error) {
	row := q.db.QueryRow(ctx, getBrandContactForAuth, viewerToken)
	var i BrandContact
	err := row.Scan(
		&i.ID,
		&i.BrandID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Email,
		&i.WhatsappNumber,
		&i.ViewerToken,
		&i.AccessPasswordHash,
		&i.TokenActive,
		&i.FutureUserAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBrandContacts = `-- name: ListBrandContacts :many
SELECT id, brand_id, first_name, last_name, role, email, whatsapp_number, viewer_token, access_password_hash, token_active, future_user_account_id, created_at, updated_at FROM brand_contacts WHERE brand_id = $1 ORDER BY created_at
`

func (q *Queries) ListBrandContacts(ctx context.Context, brandID string) ([]BrandContact, error) {
	rows, err := q.db.Query(ctx, listBrandContacts, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrandContact{}
	for rows.Next() {
		var i BrandContact
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.Email,
			&i.WhatsappNumber,
			&i.ViewerToken,
			&i.AccessPasswordHash,
			&i.TokenActive,
			&i.FutureUserAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT id, name, shortcode, industry, description, website, status, created_at, updated_at FROM brands
WHERE ($1::text = '' OR status = $1)
ORDER BY created_at DESC
LIMIT NULLIF($2::int, 0) OFFSET $3::int
`

type ListBrandsParams struct {
	Column1 string
	Column2 int32
	Column3 int32
}

func (q *Queries) ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Shortcode,
			&i.Industry,
			&i.Description,
			&i.Website,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateBrandContactPassword = `-- name: RegenerateBrandContactPassword :exec
UPDATE brand_contacts SET access_password_hash = $2, updated_at = NOW() WHERE id = $1
`

type RegenerateBrandContactPasswordParams struct {
	ID                 string
	AccessPasswordHash string
}

func (q *Queries) RegenerateBrandContactPassword(ctx context.Context, arg RegenerateBrandContactPasswordParams) error {
	_, err := q.db.Exec(ctx, regenerateBrandContactPassword, arg.ID, arg.AccessPasswordHash)
	return err
}

const shortcodeExists = `-- name: ShortcodeExists :one
SELECT EXISTS(SELECT 1 FROM brands WHERE shortcode = $1)
`

func (q *Queries) ShortcodeExists(ctx context.Context, shortcode string) (bool, error) {
	row := q.db.QueryRow(ctx, shortcodeExists, shortcode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
