// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignManagerToCampaign = `-- name: AssignManagerToCampaign :exec
INSERT INTO manager_campaign_assignments (manager_id, campaign_id, assigned_by)
VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type AssignManagerToCampaignParams struct {
	ManagerID  string
	CampaignID string
	AssignedBy string
}

func (q *Queries) AssignManagerToCampaign(ctx context.Context, arg AssignManagerToCampaignParams) error {
	_, err := q.db.Exec(ctx, assignManagerToCampaign, arg.ManagerID, arg.CampaignID, arg.AssignedBy)
	return err
}

const countCampaignsByBrandMonth = `-- name: CountCampaignsByBrandMonth :one
SELECT COUNT(*) FROM campaigns
WHERE brand_id = $1
  AND DATE_TRUNC('month', created_at) = DATE_TRUNC('month', NOW())
`

func (q *Queries) CountCampaignsByBrandMonth(ctx context.Context, brandID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCampaignsByBrandMonth, brandID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :exec
INSERT INTO campaigns (id, human_id, brand_id, name, status, campaign_type,
  total_budget, remaining_budget, market_cap, audience, target_cpa, max_cpa,
  urgency_level, cycle_length, creators_allowed, start_date, end_date)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)
`

type CreateCampaignParams struct {
	ID              string
	HumanID         string
	BrandID         string
	Name            string
	Status          string
	CampaignType    string
	TotalBudget     float64
	RemainingBudget float64
	MarketCap       string
	Audience        string
	TargetCpa       float64
	MaxCpa          float64
	UrgencyLevel    string
	CycleLength     int32
	CreatorsAllowed bool
	StartDate       pgtype.Timestamptz
	EndDate         pgtype.Timestamptz
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) error {
	_, err := q.db.Exec(ctx, createCampaign,
		arg.ID,
		arg.HumanID,
		arg.BrandID,
		arg.Name,
		arg.Status,
		arg.CampaignType,
		arg.TotalBudget,
		arg.RemainingBudget,
		arg.MarketCap,
		arg.Audience,
		arg.TargetCpa,
		arg.MaxCpa,
		arg.UrgencyLevel,
		arg.CycleLength,
		arg.CreatorsAllowed,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const decrementRemainingBudget = `-- name: DecrementRemainingBudget :exec
UPDATE campaigns
SET remaining_budget = remaining_budget - $2, updated_at = NOW()
WHERE id = $1
`

type DecrementRemainingBudgetParams struct {
	ID              string
	RemainingBudget float64
}

func (q *Queries) DecrementRemainingBudget(ctx context.Context, arg DecrementRemainingBudgetParams) error {
	_, err := q.db.Exec(ctx, decrementRemainingBudget, arg.ID, arg.RemainingBudget)
	return err
}

const getCampaignByHumanID = `-- name: GetCampaignByHumanID :one
SELECT id, human_id, brand_id, name, status, campaign_type, total_budget, remaining_budget, market_cap, audience, target_cpa, max_cpa, urgency_level, cycle_length, creators_allowed, start_date, end_date, created_at, updated_at FROM campaigns WHERE human_id = $1
`

func (q *Queries) GetCampaignByHumanID(ctx context.Context, humanID string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByHumanID, humanID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.BrandID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.MarketCap,
		&i.Audience,
		&i.TargetCpa,
		&i.MaxCpa,
		&i.UrgencyLevel,
		&i.CycleLength,
		&i.CreatorsAllowed,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, human_id, brand_id, name, status, campaign_type, total_budget, remaining_budget, market_cap, audience, target_cpa, max_cpa, urgency_level, cycle_length, creators_allowed, start_date, end_date, created_at, updated_at FROM campaigns WHERE id = $1
`

func (q *Queries) GetCampaignByID(ctx context.Context, id string) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, id)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.BrandID,
		&i.Name,
		&i.Status,
		&i.CampaignType,
		&i.TotalBudget,
		&i.RemainingBudget,
		&i.MarketCap,
		&i.Audience,
		&i.TargetCpa,
		&i.MaxCpa,
		&i.UrgencyLevel,
		&i.CycleLength,
		&i.CreatorsAllowed,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignsByManagerID = `-- name: GetCampaignsByManagerID :many
SELECT c.id, c.human_id, c.brand_id, c.name, c.status, c.campaign_type, c.total_budget, c.remaining_budget, c.market_cap, c.audience, c.target_cpa, c.max_cpa, c.urgency_level, c.cycle_length, c.creators_allowed, c.start_date, c.end_date, c.created_at, c.updated_at FROM campaigns c
JOIN manager_campaign_assignments m ON m.campaign_id = c.id
WHERE m.manager_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetCampaignsByManagerID(ctx context.Context, managerID string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, getCampaignsByManagerID, managerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.HumanID,
			&i.BrandID,
			&i.Name,
			&i.Status,
			&i.CampaignType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.MarketCap,
			&i.Audience,
			&i.TargetCpa,
			&i.MaxCpa,
			&i.UrgencyLevel,
			&i.CycleLength,
			&i.CreatorsAllowed,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCampaigns = `-- name: ListActiveCampaigns :many
SELECT id, human_id, brand_id, name, status, campaign_type, total_budget, remaining_budget, market_cap, audience, target_cpa, max_cpa, urgency_level, cycle_length, creators_allowed, start_date, end_date, created_at, updated_at FROM campaigns WHERE status = 'active' ORDER BY start_date
`

func (q *Queries) ListActiveCampaigns(ctx context.Context) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listActiveCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.HumanID,
			&i.BrandID,
			&i.Name,
			&i.Status,
			&i.CampaignType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.MarketCap,
			&i.Audience,
			&i.TargetCpa,
			&i.MaxCpa,
			&i.UrgencyLevel,
			&i.CycleLength,
			&i.CreatorsAllowed,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, human_id, brand_id, name, status, campaign_type, total_budget, remaining_budget, market_cap, audience, target_cpa, max_cpa, urgency_level, cycle_length, creators_allowed, start_date, end_date, created_at, updated_at FROM campaigns
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR brand_id = $2)
ORDER BY created_at DESC
LIMIT NULLIF($3::int, 0) OFFSET $4::int
`

type ListCampaignsParams struct {
	Column1 string
	Column2 string
	Column3 int32
	Column4 int32
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Campaign{}
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.HumanID,
			&i.BrandID,
			&i.Name,
			&i.Status,
			&i.CampaignType,
			&i.TotalBudget,
			&i.RemainingBudget,
			&i.MarketCap,
			&i.Audience,
			&i.TargetCpa,
			&i.MaxCpa,
			&i.UrgencyLevel,
			&i.CycleLength,
			&i.CreatorsAllowed,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManagersByCampaignID = `-- name: ListManagersByCampaignID :many
SELECT u.id, u.email, u.password_hash, u.role, u.provider, u.google_id, u.full_name, u.avatar_url, u.totp_secret, u.totp_enabled, u.totp_verified, u.totp_last_verified_at, u.invite_token, u.invite_expires_at, u.active, u.created_at, u.updated_at, u.status, u.deleted_at FROM users u
JOIN manager_campaign_assignments m ON m.manager_id = u.id
WHERE m.campaign_id = $1
ORDER BY u.full_name
`

func (q *Queries) ListManagersByCampaignID(ctx context.Context, campaignID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listManagersByCampaignID, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Provider,
			&i.GoogleID,
			&i.FullName,
			&i.AvatarUrl,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpVerified,
			&i.TotpLastVerifiedAt,
			&i.InviteToken,
			&i.InviteExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignManagerFromCampaign = `-- name: UnassignManagerFromCampaign :exec
DELETE FROM manager_campaign_assignments
WHERE manager_id = $1 AND campaign_id = $2
`

type UnassignManagerFromCampaignParams struct {
	ManagerID  string
	CampaignID string
}

func (q *Queries) UnassignManagerFromCampaign(ctx context.Context, arg UnassignManagerFromCampaignParams) error {
	_, err := q.db.Exec(ctx, unassignManagerFromCampaign, arg.ManagerID, arg.CampaignID)
	return err
}
