// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const flagFallbackConversions = `-- name: FlagFallbackConversions :exec
UPDATE conversion_events
SET fallback_flagged = true
WHERE cycle_id = $1
  AND DATE(occurred_at AT TIME ZONE 'UTC') = DATE($2 AT TIME ZONE 'UTC')
  AND fallback_flagged = false
`

type FlagFallbackConversionsParams struct {
	CycleID  string
	Timezone interface{}
}

func (q *Queries) FlagFallbackConversions(ctx context.Context, arg FlagFallbackConversionsParams) error {
	_, err := q.db.Exec(ctx, flagFallbackConversions, arg.CycleID, arg.Timezone)
	return err
}

const getDailyConversionCount = `-- name: GetDailyConversionCount :one
SELECT COUNT(*)::float8 FROM conversion_events
WHERE talent_id = $1 AND cycle_id = $2
  AND DATE(occurred_at AT TIME ZONE 'UTC') = DATE($3 AT TIME ZONE 'UTC')
`

type GetDailyConversionCountParams struct {
	TalentID string
	CycleID  string
	Timezone interface{}
}

func (q *Queries) GetDailyConversionCount(ctx context.Context, arg GetDailyConversionCountParams) (float64, error) {
	row := q.db.QueryRow(ctx, getDailyConversionCount, arg.TalentID, arg.CycleID, arg.Timezone)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTalentConversions = `-- name: GetTalentConversions :one
SELECT COUNT(*)::float8 FROM conversion_events
WHERE talent_id = $1 AND cycle_id = $2
`

type GetTalentConversionsParams struct {
	TalentID string
	CycleID  string
}

func (q *Queries) GetTalentConversions(ctx context.Context, arg GetTalentConversionsParams) (float64, error) {
	row := q.db.QueryRow(ctx, getTalentConversions, arg.TalentID, arg.CycleID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalConversions = `-- name: GetTotalConversions :one
SELECT COUNT(*)::float8 FROM conversion_events WHERE cycle_id = $1
`

func (q *Queries) GetTotalConversions(ctx context.Context, cycleID string) (float64, error) {
	row := q.db.QueryRow(ctx, getTotalConversions, cycleID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const lockFallbackConversions = `-- name: LockFallbackConversions :exec
UPDATE conversion_events
SET fallback_flagged = true
WHERE cycle_id = $1 AND fallback_flagged = true
`

func (q *Queries) LockFallbackConversions(ctx context.Context, cycleID string) error {
	_, err := q.db.Exec(ctx, lockFallbackConversions, cycleID)
	return err
}

const logConversionEvent = `-- name: LogConversionEvent :exec
INSERT INTO conversion_events (id, link_token, talent_id, campaign_id, cycle_id,
  pipeline_type, event_type, kpb_type, valid_lead, idempotency_key, occurred_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
`

type LogConversionEventParams struct {
	ID             string
	LinkToken      string
	TalentID       string
	CampaignID     string
	CycleID        string
	PipelineType   string
	EventType      string
	KpbType        pgtype.Text
	ValidLead      bool
	IdempotencyKey string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) LogConversionEvent(ctx context.Context, arg LogConversionEventParams) error {
	_, err := q.db.Exec(ctx, logConversionEvent,
		arg.ID,
		arg.LinkToken,
		arg.TalentID,
		arg.CampaignID,
		arg.CycleID,
		arg.PipelineType,
		arg.EventType,
		arg.KpbType,
		arg.ValidLead,
		arg.IdempotencyKey,
		arg.OccurredAt,
	)
	return err
}
