// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSlot = `-- name: AssignSlot :exec
UPDATE budget_slots SET allocated = true, talent_id = $2 WHERE id = $1
`

type AssignSlotParams struct {
	ID       string
	TalentID pgtype.Text
}

func (q *Queries) AssignSlot(ctx context.Context, arg AssignSlotParams) error {
	_, err := q.db.Exec(ctx, assignSlot, arg.ID, arg.TalentID)
	return err
}

const closeCycle = `-- name: CloseCycle :exec
UPDATE cycles
SET status = 'closed', remaining_budget = remaining_budget - $2, updated_at = NOW()
WHERE id = $1
`

type CloseCycleParams struct {
	ID              string
	RemainingBudget float64
}

func (q *Queries) CloseCycle(ctx context.Context, arg CloseCycleParams) error {
	_, err := q.db.Exec(ctx, closeCycle, arg.ID, arg.RemainingBudget)
	return err
}

const createCycle = `-- name: CreateCycle :exec
INSERT INTO cycles (id, human_id, campaign_id, cycle_number, status, cycle_budget,
  remaining_budget, cycle_objective, campaign_type, kpb_config, z_factor, start_date, end_date)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type CreateCycleParams struct {
	ID              string
	HumanID         string
	CampaignID      string
	CycleNumber     int32
	Status          string
	CycleBudget     float64
	RemainingBudget float64
	CycleObjective  string
	CampaignType    string
	KpbConfig       []byte
	ZFactor         float64
	StartDate       pgtype.Timestamptz
	EndDate         pgtype.Timestamptz
}

func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) error {
	_, err := q.db.Exec(ctx, createCycle,
		arg.ID,
		arg.HumanID,
		arg.CampaignID,
		arg.CycleNumber,
		arg.Status,
		arg.CycleBudget,
		arg.RemainingBudget,
		arg.CycleObjective,
		arg.CampaignType,
		arg.KpbConfig,
		arg.ZFactor,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const getActiveCycles = `-- name: GetActiveCycles :many
SELECT id, human_id, campaign_id, cycle_number, status, cycle_budget, remaining_budget, cycle_objective, campaign_type, kpb_config, z_factor, start_date, end_date, created_at, updated_at FROM cycles WHERE status = 'active' ORDER BY start_date
`

func (q *Queries) GetActiveCycles(ctx context.Context) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, getActiveCycles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.HumanID,
			&i.CampaignID,
			&i.CycleNumber,
			&i.Status,
			&i.CycleBudget,
			&i.RemainingBudget,
			&i.CycleObjective,
			&i.CampaignType,
			&i.KpbConfig,
			&i.ZFactor,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCycleByID = `-- name: GetCycleByID :one
SELECT id, human_id, campaign_id, cycle_number, status, cycle_budget, remaining_budget, cycle_objective, campaign_type, kpb_config, z_factor, start_date, end_date, created_at, updated_at FROM cycles WHERE id = $1
`

func (q *Queries) GetCycleByID(ctx context.Context, id string) (Cycle, error) {
	row := q.db.QueryRow(ctx, getCycleByID, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.CampaignID,
		&i.CycleNumber,
		&i.Status,
		&i.CycleBudget,
		&i.RemainingBudget,
		&i.CycleObjective,
		&i.CampaignType,
		&i.KpbConfig,
		&i.ZFactor,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCyclesByCampaign = `-- name: ListCyclesByCampaign :many
SELECT id, human_id, campaign_id, cycle_number, status, cycle_budget, remaining_budget, cycle_objective, campaign_type, kpb_config, z_factor, start_date, end_date, created_at, updated_at FROM cycles WHERE campaign_id = $1 ORDER BY cycle_number
`

func (q *Queries) ListCyclesByCampaign(ctx context.Context, campaignID string) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listCyclesByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.HumanID,
			&i.CampaignID,
			&i.CycleNumber,
			&i.Status,
			&i.CycleBudget,
			&i.RemainingBudget,
			&i.CycleObjective,
			&i.CampaignType,
			&i.KpbConfig,
			&i.ZFactor,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlotsByCycle = `-- name: ListSlotsByCycle :many
SELECT id, cycle_id, tier_value, slot_index, allocated, talent_id FROM budget_slots WHERE cycle_id = $1 ORDER BY tier_value, slot_index
`

func (q *Queries) ListSlotsByCycle(ctx context.Context, cycleID string) ([]BudgetSlot, error) {
	rows, err := q.db.Query(ctx, listSlotsByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetSlot{}
	for rows.Next() {
		var i BudgetSlot
		if err := rows.Scan(
			&i.ID,
			&i.CycleID,
			&i.TierValue,
			&i.SlotIndex,
			&i.Allocated,
			&i.TalentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
