// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_dispatches.sql

package postgres

import (
	"context"
)

const emailDispatchExists = `-- name: EmailDispatchExists :one
SELECT EXISTS(
  SELECT 1 FROM email_dispatches
  WHERE entity_type = $1 AND entity_id = $2 AND template_key = $3 AND recipient = $4
)
`

type EmailDispatchExistsParams struct {
	EntityType  string
	EntityID    string
	TemplateKey string
	Recipient   string
}

func (q *Queries) EmailDispatchExists(ctx context.Context, arg EmailDispatchExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, emailDispatchExists,
		arg.EntityType,
		arg.EntityID,
		arg.TemplateKey,
		arg.Recipient,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEmailDispatch = `-- name: InsertEmailDispatch :execrows
INSERT INTO email_dispatches (entity_type, entity_id, template_key, recipient)
VALUES ($1, $2, $3, $4)
ON CONFLICT (entity_type, entity_id, template_key, recipient) DO NOTHING
`

type InsertEmailDispatchParams struct {
	EntityType  string
	EntityID    string
	TemplateKey string
	Recipient   string
}

func (q *Queries) InsertEmailDispatch(ctx context.Context, arg InsertEmailDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEmailDispatch,
		arg.EntityType,
		arg.EntityID,
		arg.TemplateKey,
		arg.Recipient,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
