// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditChainTip struct {
	ID        int32
	LastHash  string
	LastSeq   int64
	UpdatedAt pgtype.Timestamptz
}

type AuditLog struct {
	ID          string
	ActorID     pgtype.Text
	ActionType  string
	EntityType  string
	EntityID    string
	BeforeState []byte
	AfterState  []byte
	CreatedAt   pgtype.Timestamptz
	RequestID   string
	Seq         pgtype.Int8
	PrevHash    string
	EntryHash   string
	Signature   string
	ArchiveUri  string
	IpAddress   string
	UserAgent   string
}

type Brand struct {
	ID          string
	Name        string
	Shortcode   string
	Industry    string
	Description string
	Website     string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	LogoUrl     string
}

type BrandContact struct {
	ID                  string
	BrandID             string
	FirstName           string
	LastName            string
	Role                string
	Email               string
	WhatsappNumber      string
	ViewerToken         string
	AccessPasswordHash  string
	TokenActive         bool
	FutureUserAccountID pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type BudgetSlot struct {
	ID        string
	CycleID   string
	TierValue int32
	SlotIndex int32
	Allocated bool
	TalentID  pgtype.Text
}

type Campaign struct {
	ID              string
	HumanID         string
	BrandID         string
	Name            string
	Status          string
	CampaignType    string
	TotalBudget     float64
	RemainingBudget float64
	MarketCap       string
	Audience        string
	TargetCpa       float64
	MaxCpa          float64
	UrgencyLevel    string
	CycleLength     int32
	CreatorsAllowed bool
	StartDate       pgtype.Timestamptz
	EndDate         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Content         []byte
}

type CampaignViewer struct {
	ID         string
	CampaignID string
	Token      string
	Name       string
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

type CategoryBaseline struct {
	Category string
	Median   float64
}

type ConversionEvent struct {
	ID              string
	LinkToken       string
	TalentID        string
	CampaignID      string
	CycleID         string
	PipelineType    string
	EventType       string
	KpbType         pgtype.Text
	ValidLead       bool
	FallbackFlagged bool
	IdempotencyKey  string
	OccurredAt      pgtype.Timestamptz
}

type Cycle struct {
	ID              string
	HumanID         string
	CampaignID      string
	CycleNumber     int32
	Status          string
	CycleBudget     float64
	RemainingBudget float64
	CycleObjective  string
	CampaignType    string
	KpbConfig       []byte
	ZFactor         float64
	StartDate       pgtype.Timestamptz
	EndDate         pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	ContentOverride []byte
}

type CycleReport struct {
	ID                            string
	CycleID                       string
	OfferDecisionLabel            pgtype.Text
	MaxSpendDecisionLabel         pgtype.Text
	PredictedDailyConversionsNext pgtype.Numeric
	GeneratedAt                   pgtype.Timestamptz
}

type EmailDispatch struct {
	ID          string
	EntityType  string
	EntityID    string
	TemplateKey string
	Recipient   string
	SentAt      pgtype.Timestamptz
}

type ManagerCampaignAssignment struct {
	ManagerID  string
	CampaignID string
	AssignedBy string
	AssignedAt pgtype.Timestamptz
}

type PayoutRecord struct {
	ID               string
	TalentID         string
	CycleID          string
	CampaignID       string
	PipelineType     string
	Status           string
	AllocatedBudget  float64
	GrossBase        float64
	KpbTotal         float64
	GrossTotal       float64
	CostPerUnit      float64
	CapApplied       float64
	CapExceeded      bool
	ExcessForfeited  float64
	CommissionRate   float64
	CommissionAmount float64
	ENet             float64
	ScaleFactor      float64
	FinalPayout      float64
	KpbPoolSource    string
	FallbackFlagged  bool
	ReportSubmitted  bool
	AdminOverride    bool
	OverrideReason   string
	ApprovedBy       pgtype.Text
	ApprovedAt       pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	FailureReason    string
	RetryCount       int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Session struct {
	ID           string
	UserID       string
	Token        string
	IpAddress    string
	UserAgent    string
	LastActiveAt pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	Invalidated  bool
}

type Talent struct {
	ID               string
	UserID           string
	Category         string
	Status           string
	Skills           []string
	RatePerDay       float64
	MaxTier          int32
	Bio              string
	PortfolioUrl     string
	ReportCompliance float64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type TalentAssignment struct {
	TalentID         string
	CampaignID       string
	CycleID          string
	SlotID           string
	RoleLabel        string
	Status           string
	AssignmentSource string
	PdcMode          string
	PdcValue         float64
	MatchScore       float64
	MatchDm          float64
	MatchGp          float64
	MatchOh          float64
	PinnedTier       int32
	EffectiveTier    int32
	BreakoutFlag     bool
	AssignedAt       pgtype.Timestamptz
}

type TalentBaseline struct {
	TalentID  string
	AlphaLt   float64
	BetaLt    float64
	LambdaLt  float64
	SigmaHist float64
	DeltaLt   float64
	UpdatedAt pgtype.Timestamptz
}

type TalentCycleState struct {
	TalentID     string
	CycleID      string
	CycleNumber  int32
	PdcAllocated float64
	PdcNext      float64
	Pattern      string
	DeltaSt      float64
	UpdatedAt    pgtype.Timestamptz
}

type TalentReport struct {
	ID               string
	TalentID         string
	CycleID          string
	SubmittedAt      pgtype.Timestamptz
	DeadlineAt       pgtype.Timestamptz
	AudienceReached  pgtype.Text
	OfferPromoted    pgtype.Text
	FrictionScore    pgtype.Numeric
	AudienceReaction pgtype.Text
	BlockerCategory  pgtype.Text
	Status           string
	CreatedAt        pgtype.Timestamptz
}

type TrackingLink struct {
	ID         string
	CampaignID string
	CycleID    string
	TalentID   string
	Token      string
	Active     bool
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID                 string
	Email              string
	PasswordHash       pgtype.Text
	Role               string
	Provider           string
	GoogleID           pgtype.Text
	FullName           string
	AvatarUrl          string
	TotpSecret         string
	TotpEnabled        bool
	TotpVerified       bool
	TotpLastVerifiedAt pgtype.Timestamptz
	InviteToken        pgtype.Text
	InviteExpiresAt    pgtype.Timestamptz
	Active             bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	Status             string
	DeletedAt          pgtype.Timestamptz
	PhoneNumber        string
}

type ViewerPassword struct {
	ID           string
	ViewerID     string
	PasswordHash string
	Label        string
	Active       bool
	CreatedAt    pgtype.Timestamptz
}
