// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayoutRecord = `-- name: CreatePayoutRecord :exec
INSERT INTO payout_records (id, talent_id, cycle_id, campaign_id, pipeline_type,
  status, allocated_budget, gross_base, kpb_total, gross_total, cost_per_unit,
  cap_applied, cap_exceeded, excess_forfeited, commission_rate, commission_amount,
  e_net, scale_factor, final_payout, kpb_pool_source, fallback_flagged,
  report_submitted, admin_override, override_reason, approved_by, approved_at,
  paid_at, failure_reason, retry_count)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26,$27,$28,$29)
`

type CreatePayoutRecordParams struct {
	ID               string
	TalentID         string
	CycleID          string
	CampaignID       string
	PipelineType     string
	Status           string
	AllocatedBudget  float64
	GrossBase        float64
	KpbTotal         float64
	GrossTotal       float64
	CostPerUnit      float64
	CapApplied       float64
	CapExceeded      bool
	ExcessForfeited  float64
	CommissionRate   float64
	CommissionAmount float64
	ENet             float64
	ScaleFactor      float64
	FinalPayout      float64
	KpbPoolSource    string
	FallbackFlagged  bool
	ReportSubmitted  bool
	AdminOverride    bool
	OverrideReason   string
	ApprovedBy       pgtype.Text
	ApprovedAt       pgtype.Timestamptz
	PaidAt           pgtype.Timestamptz
	FailureReason    string
	RetryCount       int32
}

func (q *Queries) CreatePayoutRecord(ctx context.Context, arg CreatePayoutRecordParams) error {
	_, err := q.db.Exec(ctx, createPayoutRecord,
		arg.ID,
		arg.TalentID,
		arg.CycleID,
		arg.CampaignID,
		arg.PipelineType,
		arg.Status,
		arg.AllocatedBudget,
		arg.GrossBase,
		arg.KpbTotal,
		arg.GrossTotal,
		arg.CostPerUnit,
		arg.CapApplied,
		arg.CapExceeded,
		arg.ExcessForfeited,
		arg.CommissionRate,
		arg.CommissionAmount,
		arg.ENet,
		arg.ScaleFactor,
		arg.FinalPayout,
		arg.KpbPoolSource,
		arg.FallbackFlagged,
		arg.ReportSubmitted,
		arg.AdminOverride,
		arg.OverrideReason,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.PaidAt,
		arg.FailureReason,
		arg.RetryCount,
	)
	return err
}

const getPayoutRecord = `-- name: GetPayoutRecord :one
SELECT id, talent_id, cycle_id, campaign_id, pipeline_type, status, allocated_budget, gross_base, kpb_total, gross_total, cost_per_unit, cap_applied, cap_exceeded, excess_forfeited, commission_rate, commission_amount, e_net, scale_factor, final_payout, kpb_pool_source, fallback_flagged, report_submitted, admin_override, override_reason, approved_by, approved_at, paid_at, failure_reason, retry_count, created_at, updated_at FROM payout_records WHERE talent_id = $1 AND cycle_id = $2
`

type GetPayoutRecordParams struct {
	TalentID string
	CycleID  string
}

func (q *Queries) GetPayoutRecord(ctx context.Context, arg GetPayoutRecordParams) (PayoutRecord, error) {
	row := q.db.QueryRow(ctx, getPayoutRecord, arg.TalentID, arg.CycleID)
	var i PayoutRecord
	err := row.Scan(
		&i.ID,
		&i.TalentID,
		&i.CycleID,
		&i.CampaignID,
		&i.PipelineType,
		&i.Status,
		&i.AllocatedBudget,
		&i.GrossBase,
		&i.KpbTotal,
		&i.GrossTotal,
		&i.CostPerUnit,
		&i.CapApplied,
		&i.CapExceeded,
		&i.ExcessForfeited,
		&i.CommissionRate,
		&i.CommissionAmount,
		&i.ENet,
		&i.ScaleFactor,
		&i.FinalPayout,
		&i.KpbPoolSource,
		&i.FallbackFlagged,
		&i.ReportSubmitted,
		&i.AdminOverride,
		&i.OverrideReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayoutsByCycle = `-- name: ListPayoutsByCycle :many
SELECT id, talent_id, cycle_id, campaign_id, pipeline_type, status, allocated_budget, gross_base, kpb_total, gross_total, cost_per_unit, cap_applied, cap_exceeded, excess_forfeited, commission_rate, commission_amount, e_net, scale_factor, final_payout, kpb_pool_source, fallback_flagged, report_submitted, admin_override, override_reason, approved_by, approved_at, paid_at, failure_reason, retry_count, created_at, updated_at FROM payout_records WHERE cycle_id = $1 ORDER BY created_at
`

func (q *Queries) ListPayoutsByCycle(ctx context.Context, cycleID string) ([]PayoutRecord, error) {
	rows, err := q.db.Query(ctx, listPayoutsByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutRecord{}
	for rows.Next() {
		var i PayoutRecord
		if err := rows.Scan(
			&i.ID,
			&i.TalentID,
			&i.CycleID,
			&i.CampaignID,
			&i.PipelineType,
			&i.Status,
			&i.AllocatedBudget,
			&i.GrossBase,
			&i.KpbTotal,
			&i.GrossTotal,
			&i.CostPerUnit,
			&i.CapApplied,
			&i.CapExceeded,
			&i.ExcessForfeited,
			&i.CommissionRate,
			&i.CommissionAmount,
			&i.ENet,
			&i.ScaleFactor,
			&i.FinalPayout,
			&i.KpbPoolSource,
			&i.FallbackFlagged,
			&i.ReportSubmitted,
			&i.AdminOverride,
			&i.OverrideReason,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.PaidAt,
			&i.FailureReason,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayoutsByTalent = `-- name: ListPayoutsByTalent :many
SELECT id, talent_id, cycle_id, campaign_id, pipeline_type, status, allocated_budget, gross_base, kpb_total, gross_total, cost_per_unit, cap_applied, cap_exceeded, excess_forfeited, commission_rate, commission_amount, e_net, scale_factor, final_payout, kpb_pool_source, fallback_flagged, report_submitted, admin_override, override_reason, approved_by, approved_at, paid_at, failure_reason, retry_count, created_at, updated_at FROM payout_records WHERE talent_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPayoutsByTalent(ctx context.Context, talentID string) ([]PayoutRecord, error) {
	rows, err := q.db.Query(ctx, listPayoutsByTalent, talentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayoutRecord{}
	for rows.Next() {
		var i PayoutRecord
		if err := rows.Scan(
			&i.ID,
			&i.TalentID,
			&i.CycleID,
			&i.CampaignID,
			&i.PipelineType,
			&i.Status,
			&i.AllocatedBudget,
			&i.GrossBase,
			&i.KpbTotal,
			&i.GrossTotal,
			&i.CostPerUnit,
			&i.CapApplied,
			&i.CapExceeded,
			&i.ExcessForfeited,
			&i.CommissionRate,
			&i.CommissionAmount,
			&i.ENet,
			&i.ScaleFactor,
			&i.FinalPayout,
			&i.KpbPoolSource,
			&i.FallbackFlagged,
			&i.ReportSubmitted,
			&i.AdminOverride,
			&i.OverrideReason,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.PaidAt,
			&i.FailureReason,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
