// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token, ip_address, user_agent, expires_at)
VALUES ($1,$2,$3,$4,$5)
`

type CreateSessionParams struct {
	UserID    string
	Token     string
	IpAddress string
	UserAgent string
	ExpiresAt pgtype.Timestamptz
}

// id is DB-generated (gen_random_uuid); do not insert it or empty-string PKs recur.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, token, ip_address, user_agent, last_active_at, expires_at, invalidated FROM sessions
WHERE token = $1 AND invalidated = false AND expires_at > NOW()
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.Invalidated,
	)
	return i, err
}

const invalidateAllUserSessions = `-- name: InvalidateAllUserSessions :exec
UPDATE sessions SET invalidated = true WHERE user_id = $1
`

func (q *Queries) InvalidateAllUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, invalidateAllUserSessions, userID)
	return err
}

const invalidateSession = `-- name: InvalidateSession :exec
UPDATE sessions SET invalidated = true WHERE token = $1
`

func (q *Queries) InvalidateSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, invalidateSession, token)
	return err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, token, ip_address, user_agent, last_active_at, expires_at, invalidated FROM sessions WHERE user_id = $1 ORDER BY last_active_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.IpAddress,
			&i.UserAgent,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.Invalidated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_active_at = $2 WHERE token = $1
`

type TouchSessionParams struct {
	Token        string
	LastActiveAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.Token, arg.LastActiveAt)
	return err
}
