// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: talents.sql

package postgres

import (
	"context"
)

const createTalent = `-- name: CreateTalent :exec
INSERT INTO talents (id, user_id, category, status, skills, rate_per_day, max_tier,
  bio, portfolio_url, report_compliance)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type CreateTalentParams struct {
	ID               string
	UserID           string
	Category         string
	Status           string
	Skills           []string
	RatePerDay       float64
	MaxTier          int32
	Bio              string
	PortfolioUrl     string
	ReportCompliance float64
}

func (q *Queries) CreateTalent(ctx context.Context, arg CreateTalentParams) error {
	_, err := q.db.Exec(ctx, createTalent,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Status,
		arg.Skills,
		arg.RatePerDay,
		arg.MaxTier,
		arg.Bio,
		arg.PortfolioUrl,
		arg.ReportCompliance,
	)
	return err
}

const getTalentByID = `-- name: GetTalentByID :one
SELECT id, user_id, category, status, skills, rate_per_day, max_tier, bio, portfolio_url, report_compliance, created_at, updated_at FROM talents WHERE id = $1
`

func (q *Queries) GetTalentByID(ctx context.Context, id string) (Talent, error) {
	row := q.db.QueryRow(ctx, getTalentByID, id)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Status,
		&i.Skills,
		&i.RatePerDay,
		&i.MaxTier,
		&i.Bio,
		&i.PortfolioUrl,
		&i.ReportCompliance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTalentByUserID = `-- name: GetTalentByUserID :one
SELECT id, user_id, category, status, skills, rate_per_day, max_tier, bio, portfolio_url, report_compliance, created_at, updated_at FROM talents WHERE user_id = $1
`

func (q *Queries) GetTalentByUserID(ctx context.Context, userID string) (Talent, error) {
	row := q.db.QueryRow(ctx, getTalentByUserID, userID)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Status,
		&i.Skills,
		&i.RatePerDay,
		&i.MaxTier,
		&i.Bio,
		&i.PortfolioUrl,
		&i.ReportCompliance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTalents = `-- name: ListAllTalents :many
SELECT id, user_id, category, status, skills, rate_per_day, max_tier, bio, portfolio_url, report_compliance, created_at, updated_at FROM talents ORDER BY created_at
`

func (q *Queries) ListAllTalents(ctx context.Context) ([]Talent, error) {
	rows, err := q.db.Query(ctx, listAllTalents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Talent{}
	for rows.Next() {
		var i Talent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Status,
			&i.Skills,
			&i.RatePerDay,
			&i.MaxTier,
			&i.Bio,
			&i.PortfolioUrl,
			&i.ReportCompliance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalents = `-- name: ListTalents :many
SELECT id, user_id, category, status, skills, rate_per_day, max_tier, bio, portfolio_url, report_compliance, created_at, updated_at FROM talents
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR category = $2)
ORDER BY created_at DESC
LIMIT NULLIF($3::int, 0) OFFSET $4::int
`

type ListTalentsParams struct {
	Column1 string
	Column2 string
	Column3 int32
	Column4 int32
}

func (q *Queries) ListTalents(ctx context.Context, arg ListTalentsParams) ([]Talent, error) {
	rows, err := q.db.Query(ctx, listTalents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Talent{}
	for rows.Next() {
		var i Talent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Status,
			&i.Skills,
			&i.RatePerDay,
			&i.MaxTier,
			&i.Bio,
			&i.PortfolioUrl,
			&i.ReportCompliance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
