// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracking.sql

package postgres

import (
	"context"
)

const createTrackingLink = `-- name: CreateTrackingLink :exec
INSERT INTO tracking_links (id, campaign_id, cycle_id, talent_id, token, active)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateTrackingLinkParams struct {
	ID         string
	CampaignID string
	CycleID    string
	TalentID   string
	Token      string
	Active     bool
}

func (q *Queries) CreateTrackingLink(ctx context.Context, arg CreateTrackingLinkParams) error {
	_, err := q.db.Exec(ctx, createTrackingLink,
		arg.ID,
		arg.CampaignID,
		arg.CycleID,
		arg.TalentID,
		arg.Token,
		arg.Active,
	)
	return err
}

const getTrackingLinkByToken = `-- name: GetTrackingLinkByToken :one
SELECT id, campaign_id, cycle_id, talent_id, token, active, created_at FROM tracking_links WHERE token = $1
`

func (q *Queries) GetTrackingLinkByToken(ctx context.Context, token string) (TrackingLink, error) {
	row := q.db.QueryRow(ctx, getTrackingLinkByToken, token)
	var i TrackingLink
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.CycleID,
		&i.TalentID,
		&i.Token,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listTrackingLinksByCycle = `-- name: ListTrackingLinksByCycle :many
SELECT id, campaign_id, cycle_id, talent_id, token, active, created_at FROM tracking_links WHERE cycle_id = $1 ORDER BY created_at
`

func (q *Queries) ListTrackingLinksByCycle(ctx context.Context, cycleID string) ([]TrackingLink, error) {
	rows, err := q.db.Query(ctx, listTrackingLinksByCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackingLink{}
	for rows.Next() {
		var i TrackingLink
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CycleID,
			&i.TalentID,
			&i.Token,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
