// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (email, password_hash, role, provider, google_id, full_name,
  avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at,
  invite_token, invite_expires_at, active, status, deleted_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
`

type CreateUserParams struct {
	Email              string
	PasswordHash       pgtype.Text
	Role               string
	Provider           string
	GoogleID           pgtype.Text
	FullName           string
	AvatarUrl          string
	TotpSecret         string
	TotpEnabled        bool
	TotpVerified       bool
	TotpLastVerifiedAt pgtype.Timestamptz
	InviteToken        pgtype.Text
	InviteExpiresAt    pgtype.Timestamptz
	Active             bool
	Status             string
	DeletedAt          pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Provider,
		arg.GoogleID,
		arg.FullName,
		arg.AvatarUrl,
		arg.TotpSecret,
		arg.TotpEnabled,
		arg.TotpVerified,
		arg.TotpLastVerifiedAt,
		arg.InviteToken,
		arg.InviteExpiresAt,
		arg.Active,
		arg.Status,
		arg.DeletedAt,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, provider, google_id, full_name, avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at, invite_token, invite_expires_at, active, created_at, updated_at, status, deleted_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Provider,
		&i.GoogleID,
		&i.FullName,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerified,
		&i.TotpLastVerifiedAt,
		&i.InviteToken,
		&i.InviteExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, password_hash, role, provider, google_id, full_name, avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at, invite_token, invite_expires_at, active, created_at, updated_at, status, deleted_at FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Provider,
		&i.GoogleID,
		&i.FullName,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerified,
		&i.TotpLastVerifiedAt,
		&i.InviteToken,
		&i.InviteExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, provider, google_id, full_name, avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at, invite_token, invite_expires_at, active, created_at, updated_at, status, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Provider,
		&i.GoogleID,
		&i.FullName,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerified,
		&i.TotpLastVerifiedAt,
		&i.InviteToken,
		&i.InviteExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByInviteToken = `-- name: GetUserByInviteToken :one
SELECT id, email, password_hash, role, provider, google_id, full_name, avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at, invite_token, invite_expires_at, active, created_at, updated_at, status, deleted_at FROM users WHERE invite_token = $1 AND invite_expires_at > NOW()
`

func (q *Queries) GetUserByInviteToken(ctx context.Context, inviteToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByInviteToken, inviteToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Provider,
		&i.GoogleID,
		&i.FullName,
		&i.AvatarUrl,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerified,
		&i.TotpLastVerifiedAt,
		&i.InviteToken,
		&i.InviteExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, provider, google_id, full_name, avatar_url, totp_secret, totp_enabled, totp_verified, totp_last_verified_at, invite_token, invite_expires_at, active, created_at, updated_at, status, deleted_at FROM users
WHERE ($1::text = '' OR role = $1)
  AND ($2::boolean IS NULL OR active = $2)
  AND ($3::text = '' OR status = $3)
ORDER BY created_at DESC
`

type ListUsersParams struct {
	Column1 string
	Column2 bool
	Column3 string
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Provider,
			&i.GoogleID,
			&i.FullName,
			&i.AvatarUrl,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpVerified,
			&i.TotpLastVerifiedAt,
			&i.InviteToken,
			&i.InviteExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
