// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: viewers.sql

package postgres

import (
	"context"
)

const addViewerPassword = `-- name: AddViewerPassword :exec
INSERT INTO viewer_passwords (id, viewer_id, password_hash, label, active)
VALUES ($1,$2,$3,$4,$5)
`

type AddViewerPasswordParams struct {
	ID           string
	ViewerID     string
	PasswordHash string
	Label        string
	Active       bool
}

func (q *Queries) AddViewerPassword(ctx context.Context, arg AddViewerPasswordParams) error {
	_, err := q.db.Exec(ctx, addViewerPassword,
		arg.ID,
		arg.ViewerID,
		arg.PasswordHash,
		arg.Label,
		arg.Active,
	)
	return err
}

const createViewer = `-- name: CreateViewer :exec
INSERT INTO campaign_viewers (id, campaign_id, token, name, active)
VALUES ($1,$2,$3,$4,$5)
`

type CreateViewerParams struct {
	ID         string
	CampaignID string
	Token      string
	Name       string
	Active     bool
}

func (q *Queries) CreateViewer(ctx context.Context, arg CreateViewerParams) error {
	_, err := q.db.Exec(ctx, createViewer,
		arg.ID,
		arg.CampaignID,
		arg.Token,
		arg.Name,
		arg.Active,
	)
	return err
}

const deactivateViewerPassword = `-- name: DeactivateViewerPassword :exec
UPDATE viewer_passwords SET active = false WHERE id = $1
`

func (q *Queries) DeactivateViewerPassword(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateViewerPassword, id)
	return err
}

const getAllViewerPasswords = `-- name: GetAllViewerPasswords :many
SELECT id, viewer_id, password_hash, label, active, created_at FROM viewer_passwords WHERE viewer_id = $1 AND active = true
`

func (q *Queries) GetAllViewerPasswords(ctx context.Context, viewerID string) ([]ViewerPassword, error) {
	rows, err := q.db.Query(ctx, getAllViewerPasswords, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewerPassword{}
	for rows.Next() {
		var i ViewerPassword
		if err := rows.Scan(
			&i.ID,
			&i.ViewerID,
			&i.PasswordHash,
			&i.Label,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getViewerByToken = `-- name: GetViewerByToken :one
SELECT id, campaign_id, token, name, active, created_at FROM campaign_viewers WHERE token = $1
`

func (q *Queries) GetViewerByToken(ctx context.Context, token string) (CampaignViewer, error) {
	row := q.db.QueryRow(ctx, getViewerByToken, token)
	var i CampaignViewer
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Token,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listViewerPasswords = `-- name: ListViewerPasswords :many
SELECT id, viewer_id, password_hash, label, active, created_at FROM viewer_passwords WHERE viewer_id = $1 AND active = true ORDER BY created_at
`

func (q *Queries) ListViewerPasswords(ctx context.Context, viewerID string) ([]ViewerPassword, error) {
	rows, err := q.db.Query(ctx, listViewerPasswords, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewerPassword{}
	for rows.Next() {
		var i ViewerPassword
		if err := rows.Scan(
			&i.ID,
			&i.ViewerID,
			&i.PasswordHash,
			&i.Label,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewersByCampaign = `-- name: ListViewersByCampaign :many
SELECT id, campaign_id, token, name, active, created_at FROM campaign_viewers WHERE campaign_id = $1 ORDER BY created_at
`

func (q *Queries) ListViewersByCampaign(ctx context.Context, campaignID string) ([]CampaignViewer, error) {
	rows, err := q.db.Query(ctx, listViewersByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CampaignViewer{}
	for rows.Next() {
		var i CampaignViewer
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Token,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
